#analysis of inference data

import numpy as np
import matplotlib.pyplot as plt

'''
- THEN MAKE ANALYSIS SCRIPT W FUNC TO GRAB PROBS AND TIC THAT ARE OVER A CERTAIN THRESHOLD SO I CAN LOOK AT THEM MORE AND SEE IF THESE ARE ACTUAL GOOD CANDIDATES 
- LAST THEN MAKE PLOT FUNC TO TAKE THOSE CANDIDATES FOR ME TO LOOK AT BY EYE LIKE THE CHECK NOISY SCRIPT AND HOPEFULLY ITS OBVIOUS 
'''
